tab:
  serverName: "uhh"
  discordLink: "uhm"
  webstoreLink: "hmph"

spawn:
  # SpawnTimer: How long the player must wait in seconds before /spawn teleports them to spawn
  # Set to 0 (or below) to disable the timer
  # Default: 3
  spawnTimer: 3


#testWord: 'uwu'
#testNumber: 69
#testBoolean: true
#testStringList:
#  - 'owo'
#  - 'rawr'
#  - 'meow'
#attackSpeed: 4
#noDamageTicks: 10
#Knockback:
#  XZ: 1.0
#  Y: 1.0
#  AirXZ: 1.0