name: UwUCore
version: '${project.version}'
main: me.aroze.uwucore.UwUCore
api-version: 1.18
authors: [ Aroze ]
description: A simple set of core commands for your Minecraft server!
commands:
  colouredArmor:
    aliases: [ coloredarmor, coloredarmour, colouredarmour ]
  broadcast:
    aliases: [ bc, announce ]
  heal: {}
  console: {}
  config: {}
  test: {}